name: Update Git Tag

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get the current tag
        id: current_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Calculate new tag
        id: new_tag
        run: |
          current_tag=${{ steps.current_tag.outputs.tag }}
          IFS='.' read -r -a parts <<< "$current_tag"
          ((parts[2]++))
          new_tag="${parts[0]}.${parts[1]}.${parts[2]}"
          echo ::set-output name=tag::$new_tag

      - name: Create and push new tag
        env:
          NEW_TAG: ${{ steps.new_tag.outputs.tag }}
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG