name: Deploy Flask App

on:
  push:
    tags:
      - 'v*'  # Trigger only for tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Deploy Application
        run: |
          # Add your deployment steps here (e.g., push to AWS, Azure, or another server)
          echo "Deploying app with version ${GITHUB_REF#refs/tags/}"
          
      - name: Tag version and deploy
        run: |
          git tag -a ${{ github.ref }} -m "Release version ${{ github.ref }}"
          git push origin ${{ github.ref }}
