name: Update Git Tag

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get the current tag
        id: current_tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Calculate new tag
        id: new_tag
        run: |
          current_tag=${{ env.tag }}
          IFS='.' read -r -a parts <<< "$current_tag"
          ((parts[2]++))
          new_tag="${parts[0]}.${parts[1]}.${parts[2]}"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create and push new tag
        env:
          NEW_TAG: ${{ env.new_tag }}
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG