name: Update Git Tag

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Added to fetch all tags

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get the current tag
        id: current_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "CURRENT_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Calculate new tag
        id: new_tag
        run: |
          CURRENT_TAG="${CURRENT_TAG#v}"  # Remove 'v' prefix if present
          IFS='.' read -r major minor patch <<< "$CURRENT_TAG"
          NEW_PATCH=$((patch + 1))
          NEW_TAG="v$major.$minor.$NEW_PATCH"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV

      - name: Create and push new tag
        run: |
          if ! git rev-parse "$NEW_TAG" >/dev/null 2>&1; then
            git tag $NEW_TAG
            git push origin $NEW_TAG
          else
            echo "Tag $NEW_TAG already exists"
            exit 1